language: php

php:
  - 7.3
  - 7.4
  - 8.0

install: travis_retry composer install --no-interaction --prefer-source

script:
  - XDEBUG_MODE=coverage vendor/bin/phpunit --coverage-clover=coverage.clover
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
