name: Tests

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: php-actions/composer@v5

      - name: PHPUnit Tests
        uses: php-actions/phpunit@v2
        with:
          bootstrap: vendor/autoload.php
          configuration: test/phpunit.xml
          args: "--coverage-clover=build/logs/coverage.clover"

      - name: Upload Scrutinizer coverage
        uses: sudo-bot/action-scrutinizer@latest
        with:
          cli-args: "--format=php-clover build/logs/coverage.clover"
